### ISSUE TITLE
Fails to call `fetchFromGitHub`

### ISSUE THREAD

**Issue by bandithedoge** [berberman/nvfetcher#96] opened 2023-05-12 05:12 UTC
```
nvfetcher: Error when running Shake build system:
  at want, called at src/NvFetcher.hs:165:25 in nvfetcher-0.6.0.0-Ij6CZnAde2EIKHemkCmGei:NvFetcher
* Depends on: build
  at apply1, called at src/NvFetcher/Core.hs:122:16 in nvfetcher-0.6.0.0-Ij6CZnAde2EIKHemkCmGei:NvFetcher.Core
* Depends on: Core ("raze")
  at apply1, called at src/Development/Shake/Internal/Rules/Oracle.hs:159:32 in shake-0.19.7-4176Nw2xce76rgenm3Yfj:Development.Shake.Internal.Rules.Oracle
* Depends on: OracleQ (RunFetch NoForceFetch (FetchGitHub {_fowner = "ZDoom", _frepo = "Raze", _rev = "1.7.1", _deepClone = False, _fetchSubmodules = False, _leaveDotGit = False, _name = Nothing, _sha256 = ()}))
  at command, called at src/NvFetcher/NixFetcher.hs:88:9 in nvfetcher-0.6.0.0-Ij6CZnAde2EIKHemkCmGei:NvFetcher.NixFetcher
* Raised the exception:
Development.Shake.command, system command failed
Command line: nix-prefetch fetchFromGitHub --owner ZDoom --repo Raze --rev 1.7.1
Exit code: 1
Stderr:
error: anonymous function at /nix/store/wr0nbasjdp7rzz7y7ypiajkv7w5y5y0b-source/pkgs/build-support/fetchgithub/default.nix:4:1 called without required argument 'repo'

       at /nix/store/wr0nbasjdp7rzz7y7ypiajkv7w5y5y0b-source/lib/customisation.nix:80:16:

           79|     let
           80|       result = f origArgs;
             |                ^
           81|
(use '--show-trace' to show detailed location information)
```

The full run can be found [here](https://github.com/bandithedoge/nur-packages/actions/runs/4944270928/jobs/8839572869) and the command [here](https://github.com/bandithedoge/nur-packages/actions/runs/4944270928/workflow#L44).

**Comment by fbewivpjsbsby** [comment] 2023-05-15 02:26
Same issues.
But sometimes can build successfully.
```bash
Command line: nix-prefetch fetchFromGitHub --owner c0re100 --repo qBittorrent-Enhanced-Edition --rev release-4.5.2.10
Exit code: 1
Stderr:
error: anonymous function at /nix/store/kx95l13bq13djl87bm17px8wasc0q186-source/pkgs/build-support/fetchgithub/default.nix:4:1 called without required argument 'repo'
       at /nix/store/kx95l13bq13djl87bm17px8wasc0q186-source/lib/customisation.nix:80:16:
           79|     let
           80|       result = f origArgs;
             |                ^
           81|
```
gitlab ci
```.gitlab-ci.yml
run-nvfetcher:
  stage: nvfetcher
  image:
    name: "nixpkgs/nix-unstable:latest"
  variables:
    CACHIX_CACHE_NAME: berberman
  before_script:
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
    - export NIX_PATH=nixpkgs=channel:nixos-unstable
    - nix-channel --update
    - nix-env --install --attr nixpkgs.cachix
    - cachix use "$CACHIX_CACHE_NAME"
    - export CACHIX_SIGNING_KEY="$CACHIX_SIGNING_KEY"
  script:
    - mkdir -p "$HOME/.config/nix"
    - echo 'experimental-features = nix-command flakes' > "$HOME/.config/nix/nix.conf"
    - nix develop --command runghc Update
    - nix develop --profile dev && cachix push "$CACHIX_CACHE_NAME" dev
    - nix flake check
  artifacts:
    paths:
    - variables
  only:
    - update
```

**Comment by pschyska** [comment] 2023-05-15 12:55
I got the same issues with `fetchFromGithub`, additionally with `git`:

```shell
nvfetcher: Error when running Shake build system:
  at want, called at src/NvFetcher.hs:165:25 in nvfetcher-0.6.0.0-29ULY81FORnAG8jA9OahX3:NvFetcher
* Depends on: build
* Depends on: Core ("tree-sitter")
  at apply1, called at src/Development/Shake/Internal/Rules/Oracle.hs:159:32 in shake-0.19.7-GhGYRI3Tt4NHzB99LTyOQW:Development.Shake.Internal.Rules.Oracle
* Depends on: OracleQ (RunFetch NoForceFetch (FetchGit {_furl = "https://github.com/tree-sitter/tree-sitter.git", _rev = "91e4d940169a0c0b024560632ef53c4f119117ca", _deepClone = False, _fetchSubmodules = False, _leaveDotGit = False, _name = Nothing, _sha256 = ()}))
  at command, called at src/NvFetcher/NixFetcher.hs:74:9 in nvfetcher-0.6.0.0-29ULY81FORnAG8jA9OahX3:NvFetcher.NixFetcher
* Raised the exception:
Development.Shake.command, system command failed
Command line: nix-prefetch fetchgit --url https://github.com/tree-sitter/tree-sitter.git --rev 91e4d940169a0c0b024560632ef53c4f119117ca
Exit code: 1
Stderr:
error: anonymous function at /nix/store/ya5b1l14bf3b2miq4fw70ykfzbgnlpxg-source/pkgs/build-support/fetchgit/default.nix:14:1 called without required argument 'url'

       at /nix/store/ya5b1l14bf3b2miq4fw70ykfzbgnlpxg-source/lib/customisation.nix:80:16:

           79|     let
           80|       result = f origArgs;
             |                ^
           81|
(use '--show-trace' to show detailed location information)
```
`nix-prefetch fetchgit --url https://github.com/tree-sitter/tree-sitter.git --rev 91e4d940169a0c0b024560632ef53c4f119117ca` stand-alone doesn't work either with the same error.
I suspect it's a nix-prefetch issue.
Is there some way to make nvfetcher user standard tooling, e.g. `nix flake prefetch` or `nix store prefetch-file`?

**Comment by bandithedoge** [comment] 2023-05-15 16:09
It seems like with every run it fails on a different repo:

https://github.com/bandithedoge/nur-packages/actions/runs/4965296000/jobs/8886015864#step:7:401

https://github.com/bandithedoge/nur-packages/actions/runs/4970735608/jobs/8894783470#step:7:413

https://github.com/bandithedoge/nur-packages/actions/runs/4970735608/jobs/8894783470#step:7:413

https://github.com/bandithedoge/nur-packages/actions/runs/4981855741/jobs/8918506149#step:7:401

**Comment by pschyska** [comment] 2023-05-16 11:16
> It seems like with every run it fails on a different repo:
> 
> https://github.com/bandithedoge/nur-packages/actions/runs/4965296000/jobs/8886015864#step:7:401
> 
> https://github.com/bandithedoge/nur-packages/actions/runs/4970735608/jobs/8894783470#step:7:413
> 
> https://github.com/bandithedoge/nur-packages/actions/runs/4970735608/jobs/8894783470#step:7:413
> 
> https://github.com/bandithedoge/nur-packages/actions/runs/4981855741/jobs/8918506149#step:7:401

I don't know for sure, but I had the feeling that shake parallelizes the tasks - it could be that multiple nix-prefetch invocations "race to fail" in your case, and that's why you get a different failure each time.

I was getting alternating failures as well, as I wrote sometimes it's a fetchFromGithub and sometimes a plain fetchgit dependency.

**Comment by pschyska** [comment] 2023-05-16 16:24
This issues seems to be caused by the linked nixpkgs PR.
nix-prefetch always uses NIX_PATH's nixpkgs, regardless of nvfetcher's nixpkgs.
I'm not sure where (nixpkgs, nix-prefetch, nvfetcher) this should be fixed.

I've added the following overlay to temporarily fix nvfetcher.:

```nix

# given inputs.oldfetchers.url = "github:nixos/nixpkgs?rev=60d3ce948ee94d2066547226fbb07e6898b7b84c";

(final: prev: {
  nix-prefetch = prev.nix-prefetch.overrideAttrs (a: {
    installPhase = ''
      ${a.installPhase}

      # work around https://github.com/berberman/nvfetcher/issues/96
      # by making nix-prefetch use nixpkgs before https://github.com/NixOS/nixpkgs/pull/158968
      wrapProgram "$out/bin/nix-prefetch" \
        --set NIX_PATH nixpkgs="${oldfetchers.outPath}"
    '';
  });
})
```

**Comment by fbewivpjsbsby** [comment] 2023-05-17 03:46
Title change to "https://github.com/NixOS/nixpkgs/pull/158968 break nvfetcher".
If use nurl can fix it but not support fetchurl.

**Comment by berberman** [comment] 2023-05-17 03:49
I see the problem here. Now I'm working on migrating from nix-prefetch to nurl.

**Closed** 2023-05-17 15:29 UTC

**Comment by pschyska** [comment] 2023-05-18 18:21
Thanks, seems to work well for me so far.

**Comment by bandithedoge** [comment] 2023-05-18 19:42
Thanks, my CI runs just confirmed it's fixed.

**Comment by teutat3s** [comment] 2023-05-19 20:56
Does somebody know a way to override nvfetcher in nixpkgs with the version from the latest commit? I can't get it to work in a flake. Alternatively, could you tag a new release so we get a working version into nixpkgs?

**Comment by bandithedoge** [comment] 2023-05-19 21:18
> Does somebody know a way to override nvfetcher in nixpkgs with the version from the latest commit? I can't get it to work in a flake. Alternatively, could you tag a new release so we get a working version into nixpkgs?

This repo provides an overlay you can use when importing nixpkgs in your flake.

**Comment by pschyska** [comment] 2023-05-20 12:07
@teutat3s are you using a library to construct your flake? e.g. for [fup](https://github.com/gytis-ivaskevicius/flake-utils-plus), something like:

```flake.nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable-small";

    fup.url = "github:gytis-ivaskevicius/flake-utils-plus";

    nvfetcher.url = "github:berberman/nvfetcher";
  };
  outputs =
    { self
    , nixpkgs
    , fup
    , nvfetcher
    , ...
    }@inputs: fup.lib.mkFlake {
      inherit self inputs;

      sharedOverlays = [
        nvfetcher.overlays.default
      ];
    };
}

```

Or however else you configure overlays.

If you are talking about https://github.com/pub-solar/os, you could add `nvfetcher.overlays.default` after this line: https://github.com/pub-solar/os/blob/main/flake.nix#L88.

**Comment by teutat3s** [comment] 2023-05-20 12:43
Oh I totally forgot about this way to use overlays. Thank you very much for the kind, detailed answers.
